name: Build Example App

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}

    strategy:
      fail-fast: false
      matrix:
        variant: [debug, release]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
    - run: dart pub get
    - run: dart format --output=none --set-exit-if-changed .
    - run: dart analyze
    - run: flutter pub get
      working-directory: example/
    #- run: flutter test
    - run: flutter build apk --${{ matrix.variant }} --verbose
      working-directory: example/
    - uses: actions/upload-artifact@v4
      with:
        name: example-apk-${{ matrix.variant }}
        path: |
          example/build/app/outputs/flutter-apk/app-${{ matrix.variant }}.apk
          example/build/reports/*

  build-ios:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        variant: [debug, release]

    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
    - run: flutter pub get
      working-directory: example/
    - run: flutter build ios --${{ matrix.variant }} --verbose --no-codesign
      working-directory: example/
