name: Publish to pub.dev

env:
  FLUTTER_VERSION: 3.24.5

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    name: 'Publish to pub.dev'
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Publish - dry run
        run: flutter pub publish --dry-run
      - name: Publish to pub.dev
        run: flutter pub publish -f
